application:
  allowed-paths:
    - /auth/
    - /account/sendEmailCode
    - /account/create
server:
  port: 8080
security:
  secret-key: ${JWT_SECRET}
  service-secret-key: ${JWT_SERVICE_SECRET}
spring:
  application:
    name: api-gateway
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000,http://localhost:3001"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: account-service-account
          uri: http://localhost:8081
          predicates:
            - Path=/account/**

        - id: account-service-user
          uri: http://localhost:8081
          predicates:
            - Path=/user/**

        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**

        - id: sports-complex-service
          uri: http://localhost:8083
          predicates:
            - Path=/sportsComplex/**